services:
    web:
      image: mdmitrym/todo-app-go:latest
      env_file:
      - .env
      environment:
        - ENV=production
      ports:
        - 8000:8000
      depends_on:
        db:
          condition: service_healthy

    db:
      restart: always
      image: postgres:latest
      env_file:
      - .env
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
        interval: 5s
        retries: 10
        start_period: 30s
        timeout: 10s
      volumes:
        - ./.database/postgres/data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - 5436:5432

    migrate:
      image: migrate/migrate:latest
      command: ["-path", "/schema", "-database", "postgres://${POSTGRES_USER}:${DB_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up"]
      depends_on:
        db:
          condition: service_healthy
      volumes:
        - ./schema:/schema